services:
  - type: web
    name: japan-tractor-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python comprehensive_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8051
